version: "3.9"

services:
  db:
    build: mysql
    volumes:
      - ./mysql/logs:/var/log/mysql
      - ./mysql/conf.d/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - db
